- azure_li_services/runtime_config.py
- test/data/config.yaml
- test/data/config_vli.yaml
Per discussion this commit adds a revised version of the
config file format to become active. Basic changes are:
* networking moved on toplevel
* blade section gets deleted, sku moved to toplevel
* storage section was reworked
* new section machine_constraints contains min_cores and
min_memory values the machine has to provide
> Cleanup of config file format

- azure_li_services/units/cleanup.py
- package/azure_li_services_spec_template
- setup.py
- systemd/azure-li-cleanup.service
- test/unit/units/cleanup_test.py
After all services got called the cleanup service kicks in
and uninstalls the azure-li-services package. This Fixes #12
> Added cleanup service

- azure_li_services/defaults.py
- azure_li_services/status_report.py
- azure_li_services/units/call.py
- azure_li_services/units/config_lookup.py
- azure_li_services/units/install.py
- azure_li_services/units/network.py
- azure_li_services/units/user.py
- test/data/some_service.report.yaml
- test/unit/defaults_test.py
- test/unit/status_report_test.py
- test/unit/units/call_test.py
- test/unit/units/config_lookup_test.py
- test/unit/units/install_test.py
- test/unit/units/network_test.py
- test/unit/units/user_test.py
In preperation to operate on an overall success or failed
state depending on the result of the individual services,
each service should have an easy way to report its result
state. The StatusReport class implements this in a way
that each service reports its state in a yaml file written
to the directory provided by get_status_report_directory().
As services are called by systemd and will run in parallel,
one file per service name is created to avoid potential
I/O conflicts on write. Issue #19
> Let services report result status

- azure_li_services/units/user.py
- test/unit/units/user_test.py
If the user setup in the config file already exists on the
system, the user service failed to add that user as it
should rather modify it. This Fixes #25
> Fixup user service for handling existing users

- azure_li_services/exceptions.py
- azure_li_services/units/install.py
- test/unit/units/install_test.py
The install service did not handle an empty list of packages
sources as an error and just proceeded without installing
packages. However in the scope of the large instance setup
it is expected that there are packages to install and if
not this is an error condition. This Fixes #26
> Handle missing packages source as error

- azure_li_services/units/user.py
- test/data/config.yaml
- test/unit/runtime_config_test.py
- test/unit/units/user_test.py
ssh files must be owned by the user they belong to. In addition
the home path of the root user is not located in the standard
home directory of users and needs an extra handling. This
Fixes #37
> Fixup ssh files ownership in user service

- azure_li_services/defaults.py
- azure_li_services/exceptions.py
- azure_li_services/units/call.py
- azure_li_services/units/config_lookup.py
- azure_li_services/units/install.py
- test/unit/defaults_test.py
- test/unit/units/call_test.py
- test/unit/units/config_lookup_test.py
- test/unit/units/install_test.py
Primarily we mount a LUN by label, but if that failed a
fallback mount from /dev/dvd kicks in. Only if that fails
the overall mount attempt has failed. This Fixes #13
> Added DVD fallback mounting sequence

- systemd/azure-li-storage.service
The storage service has to run after the network target
has been reached. This Fixes #49
> Fix service order for storage unit

- azure_li_services/schema.py
- azure_li_services/units/user.py
- test/data/config.yaml
- test/data/ssh-fake-pkey
- test/unit/runtime_config_test.py
- test/unit/units/user_test.py
Add an additional optional sub section named ssh-private-key
into the credentials section. The section allows for a name
which is the base filename of an ssh private key and the key
value encoded as base64 string. This Fixes #42
> Allow import of private key

- azure_li_services/runtime_config.py
- azure_li_services/schema.py
- azure_li_services/units/system_setup.py
- test/data/config.yaml
- test/unit/runtime_config_test.py
- test/unit/units/system_setup_test.py
Allows the setup of custom kernel crash dump values from the
yaml config file. If not specified the kdumptool calibration
results will be used to setup the high and low memory range to
store crash dumps. Please also note that the image comes with
a pre-configured crashdump setup in case the kernel crashes
before this system_setup service has done its job.
This Fixes #50
> Added kernel crash dump setup

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
For Very Large Instance platforms the reboot may not happen
without operator intervention. On EFI systems this can be
done by an efi call script: startup.nsh. This method was
preferred over setting a BIOS boot option through the Bios
menu by the Microsoft ops team. This Fixes #46
> Added reboot intervention on Very Large Instances

- systemd/azure-li-report.service
Next try to make sure the report service runs before
any getty@.service is called. The getty@.service is
configured to run after systemd-user-sessions.service
Thus we should be safe if the reporting service runs
before systemd-user-sessions.service
> Fixup runtime order of report service

- azure_li_services/schema.py
- azure_li_services/units/user.py
- test/data/config.yaml
- test/data/ssh-fake-pkey
- test/unit/runtime_config_test.py
- test/unit/units/user_test.py
Instead of specifying a base64 encoded private ssh key
string as part of the key element in the config file,
we now just read a file path reference which is expected
to exist on the storage location from where the config
file was read. The referenced file is copied as the
ssh private key of the configured user. This sets the
config file free from any secret data and Fixes #58
> Refactor reading of ssh private key

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
Regarding a discussion with Peter Schinagl the sequence
to start the saptune daemon was wrong and is fixed with
this commit. Fixes #65
> Fixup saptune startup sequence

- azure_li_services/defaults.py
- azure_li_services/status_report.py
- azure_li_services/units/cleanup.py
- azure_li_services/units/report.py
- azure_li_services/units/system_setup.py
- test/data/default_grub
- test/data/some_service.report.yaml
- test/unit/defaults_test.py
- test/unit/status_report_test.py
- test/unit/units/cleanup_test.py
- test/unit/units/report_test.py
- test/unit/units/system_setup_test.py
This patch set is two fold:
First it adds a reboot flag to the status report and extends the cleanup service to allow for reboot of
the system via kexec if 
* all services were successful
* and at least one requests for reboot of the system exists in the result reports.
Second it extends the system setup service for the crash kernel memory setup in a way that the high
value if not set via the config file is calculated based on the amount of main memory. If the pre-configured values have changed the system_setup service also activates the reboot flag in its status report
This Fixes #64
> Allow reboot of the system via kexec

- azure_li_services/units/cleanup.py
Make sure that no services module code is loaded from disk after
the cleanup service has uninstalled the azure-li-services package.
All follow up code after the uninstall must be kept in memory.
This Fixes #68
> Fixup system inconsistency on module loading

- azure_li_services/units/user.py
For the copy of the ssh private key the location providing the
key is mounted first and umounted when done. However the location
information from the mount is unknown in the scope of the final
block performing the umount. This Fixes #70
> Fixed access of unbound variable

- azure_li_services/defaults.py
- test/unit/defaults_test.py
Call the mountpoint command in mount_config_source prior to the
actual mount and perform the mount process only if the location
is not already an active mountpoint. This Fixes #74
> Check if mount location is already mounted

- azure_li_services/defaults.py
- azure_li_services/units/call.py
- azure_li_services/units/config_lookup.py
- azure_li_services/units/install.py
- azure_li_services/units/user.py
- test/unit/units/call_test.py
- test/unit/units/config_lookup_test.py
- test/unit/units/install_test.py
- test/unit/units/user_test.py
Provides a umount_config_source method in the Defaults space to allow to perform an umount which succeeds even if the mountpoint is busy. The umount is performed as Lazy unmount and detaches the filesystem from the file hierarchy now, and clean up all references to this filesystem as soon as it is not busy anymore.
This Fixes #76
> Follow up fix for mount location checkup

- azure_li_services/runtime_config.py
- azure_li_services/schema.py
- azure_li_services/units/system_setup.py
- test/data/config.yaml
- test/unit/runtime_config_test.py
- test/unit/units/system_setup_test.py
The crash dump setup deserves its own section containing
the optional high/low values as well as a new switch to
control the activation of the setup process.
This Fixes #78
> Allow to activate/deactivate the crash dump setup

- azure_li_services/units/cleanup.py
- package/azure_li_services_spec_template
- test/unit/units/cleanup_test.py
The introduction of the pre/post scripts in the package which
runs systemd macros to delete the services causes a core dump
on zypper and prevents the cleanup service from actually
uninstalling the package. Thus I suggest to delete those
pre/post actions from the package and leave this in the hand
of the cleanup service using the reset-failed command from
systemd after uninstall of the package has been performed.
This references Issue #88
> Fix inconsistent cleanup service

- azure_li_services/network.py
- azure_li_services/units/cleanup.py
- setup.cfg
- test/unit/units/cleanup_test.py
At the time of the cleanup service a file named:
* ```workload_success_is_true```  or
* ```workload_success_is_false```
will be written on the storage location the config file was read from.
At the time this file appears it's also safe to release the config file storage location from the system.
This Fixes #93
> Added workload status flag file

- azure_li_services/units/cleanup.py
- test/unit/units/cleanup_test.py
In case of a deployment error, a log file in addition to the
status flag files is written which contains the systemd
service log information from all services ran so far.
The log file is written to the storage location from which
the yaml config file was read from. It is expected that
this location is writable and offers enough space to store
the logfile. In case of an error writing the log we will
treat this as "bad luck" and continue with the cleanup.
This Fixes #96
> Write workload log file

- azure_li_services/units/user.py
The change in the schema to specify group names/id was not
handled in the code processing the setup of the ssh
authorization. As there was a group key before and after the
change in the schema but with a different result and used
only as parameters to a mocked grp.getgrnam() system call
the unit tests did not uncover the issue. This Fixes #98
> Fixed group processing in setup_ssh_authorization

- azure_li_services/instance_type.py
- azure_li_services/network.py
- azure_li_services/runtime_config.py
- azure_li_services/schema.py
- azure_li_services/units/network.py
- test/data/config.yaml
- test/data/config_vli_gen3.yaml
- test/unit/instance_type_test.py
- test/unit/network_test.py
- test/unit/runtime_config_test.py
- test/unit/units/network_test.py
__Support Custom MTU setup__
Enhanced the config schema to allow the networking attributes mtu and vlan_mtu as optional arguments to configure the maximum transfer unit for the interface and/or its virtual type.
In addition add a differentiator for the VeryLarge instance types in generation 3 and its successor. For Gen3 VeryLarge instance types the network setup was not yet defined because we haven't started to support this target. However the successor of the VeryLarge instance type is similar in the infrastructure and boot compared to the LargeInstance type and can be covered by the network service in the same way. 
This Fixes #105
> Support MTU setup for standard and vlan interfaces

- package/azure-li-services-spec-template
createrepo is no longer part of SLE15. The successor of this
package is createrepo_c an implementation in C. Therefore
the requires statement in the spec file should be changed to
the generic provides name which is createrepo-implementation
such that the package requirements are valid for SLE12 and
SLE15 builds.
> Fixup createrepo requirement

- azure_li_services/network.py
- azure_li_services/schema.py
- azure_li_services/units/network.py
- test/data/config-net-bond.yaml
- test/data/config-net-vlan-bond.yaml
- test/data/config-net-vlan.yaml
- test/data/config-net.yaml
- test/unit/network_test.py
- test/unit/units/network_test.py
Allow to setup bonding slaves on top of vlan interfaces
or direct bonding structure. Because bonding slave interfaces
comes with no ip/netmask setup the schema has to be changed
to allow interface list elements without ip and subnet_mask
fields which were required elements before.
This Fixes #114
> Added support for interface bonding

- azure_li_services/network.py
- test/unit/network_test.py
This patch is two fold, please review based on commits:
__Fixed network service vlan setup__
The vlan setup used the interface name in its ifcfg config file in the following format: ifcfg-<interface>.<vlan_id> However if the interface name is based on the MAC address that leads to a name which is longer than the fixed defined value from ```/usr/include/linux/if.h```: ```#define IFNAMSIZ 16``` and will make the network setup to fail. Therefore this patch changes the config file for the vlan setup to follow the format: ifcfg-vlan<vlan_id> which avoids that size limit. This Fixes #115
__Cleanup network service__
Delete unused elements from ifcfg configuration on suse systems
* ONBOOT, obsolete if STARTMODE is used
* VLAN, obsolete ETHERDEVICE gives the vlan type
* DEVICE, obsolete and …
> Fix network service

- azure_li_services/exceptions.py
- azure_li_services/runtime_config.py
- azure_li_services/schema.py
- azure_li_services/units/system_setup.py
- setup.cfg
- test/data/config.yaml
- test/unit/runtime_config_test.py
- test/unit/units/system_setup_test.py
In a new an optional stonith section the configuration for
the iSCSI initiator and ip address can be setup. Once present
the process to setup the iSCSI initiator as well as the
device discovery is started. This Fixes bsc#1125373 and
bsc#1125372 and Fixes #119
> Add support for iSCSI SBD device setup

- systemd/azure-li-system-setup.service
The setup of the stonith SBD device requires the network
to be up beforehand because the target is an iSCSI endpoint.
This Fixes #119
> Fixup system-setup service dependencies

- azure_li_services/units/call.py
- azure_li_services/units/install.py
- azure_li_services/units/user.py
- test/unit/units/call_test.py
- test/unit/units/install_test.py
- test/unit/units/user_test.py
If one service(A) needs the LUN and another service(B) that needs
the LUN too runs in parallel a potential race condition exists
in a way the service A could have umounted the LUN exactly at
a time service B accesses it. Thus this patch changes the
services such that only the last service, the cleanup service
umounts the LUN. This Fixes #137
> Umount LUN only on cleanup

- azure_li_services/defaults.py
- test/unit/defaults_test.py
Per request from Microsoft the location that holds the
config file and is also used for the status flag and
log should be mounted with the sync option.
This Fixes #144
> Mount LUN in sync mode

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
Check for the presence of the sap-hana profile and switch
to sapconf if not found. Activate the selected profile via
the tuned-adm control command. This Fixes #142
> Activate SAP Hana profile via tuned-adm

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
The tuned profile must be applied prior to the start of
the saptune daemon. This Fixes #149
> Fix service order on startup of saptune daemon

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
This patch is two fold
* Revert fix for service order of saptune daemon
It has turned out that the simple change in order did
not solve the problem. In fact the daemon needs to be
restarted on profile setup
* Start saptune daemon after applying profile
For some reason the saptune daemon needs to restart if a
profile has been set through the tuned-adm profile command.
This Fixes #149
> Fix saptune service setup

- azure_li_services/runtime_config.py
- azure_li_services/status_report.py
- test/unit/runtime_config_test.py
The default yaml loader is unsafe, thus we should switch
to the safe_load method. For details see: https://msg.pyyaml.org/load
> Load yaml in safe mode

- azure_li_services/network.py
- test/data/config-net-bond-vlan.yaml
- test/unit/network_test.py
vlan network definitions that uses bonding etherdevices
were missing a switch to correctly assign the ip configuration
This Fixes #164
> Fixed network setup for bonding on vlan

- systemd/azure-li-storage.service
The storage service can be used for remote storage like NFS
storage to be attached to the machine. This requires the network
to be online. Having the network only configured is not enough
it must also be online. Thus the storage service unit is extended
to wait for the network-online.target
> Extend storage service dependencies

- azure_li_services/command.py
- azure_li_services/defaults.py
- azure_li_services/logger.py
- azure_li_services/units/cleanup.py
- azure_li_services/units/config_lookup.py
- azure_li_services/units/install.py
- azure_li_services/units/machine_constraints.py
- azure_li_services/units/network.py
- azure_li_services/units/report.py
- azure_li_services/units/storage.py
- azure_li_services/units/system_setup.py
- azure_li_services/units/user.py
- test/unit/logger_test.py
- test/unit/units/call_test.py
- test/unit/units/cleanup_test.py
- test/unit/units/config_lookup_test.py
- test/unit/units/install_test.py
- test/unit/units/machine_constraints_test.py
- test/unit/units/network_test.py
- test/unit/units/report_test.py
- test/unit/units/storage_test.py
- test/unit/units/system_setup_test.py
- test/unit/units/user_test.py
Add a log file /var/log/azure-li-services.log which adds
logging information from the service process. Usually error
log information is present on the systemd level but for
checking the process, it's calls and potential further information
it's also useful to have a processing log file. The log file
will be created on the host and gets also copied to the config
lun in the same way as the systemd workload log
> Added more logging to the process

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
Only after restart of the iscsi subsystem the device nodes
from a previous device discovery gets created properly.
This Fixes #170
> Restart iscsi subsystem after device discovery

- azure_li_services/schema.py
- azure_li_services/units/user.py
- test/data/config.yaml
- test/unit/runtime_config_test.py
- test/unit/units/user_test.py
The login shell was setup based on assumption regarding other
user attributes set. This way caused some negative side effects
which lets us change the behavior. This patch does the following
* Adds a new attribute named: loginshell
* If loginshell is present the value for loginshell will be used,
if not the default /sbin/nologin applies
* All implicit assumptions for setting up the login shell
got deleted
This Fixes #178
> Change the setup of the login shell

- azure_li_services/units/system_setup.py
- test/unit/units/system_setup_test.py
One of the issues is that `saptune` is a different tool that supersedes
`sapconf`. Then the `saptune daemon restart` command will always
overwrite the profile with `saptune`. Two different tools that can't be
mixed. Only one should be used.
In case of SLES (not SLES for SAP), the sequence should be
For SLES 12
```
tuned-adm profile sap-hana
systemctl enable --now sapconf.service
```
and for SLES15
```
tuned-adm profile sapconf
systemctl enable --now sapconf.service
```
For SLES for SAP, the sequence is the same for 12 and 15:
```
saptune daemon start
saptune solution apply HANA
```
This Fixes #172
> Right sequence saptune

- images/li/sle12_sp3/config.kiwi
- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp5/config.kiwi
- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
Images for the Azure LI/VLI target are exclusive to the
x86_64 architecture. This should be expressed in the image
such that the OBS team knows it and no extra resources
are wasted by building for other architectures
> Set OBS-ExclusiveArch in all image descriptions

- .gitlab-ci.yml
Changes in the image descriptions hosted on github will
not automatically update the service in obs. This commit
adds a pipeline to run the service update from a hop
host that allows for only the service refresh command
through ssh
> Added obs github service integration

- .gitlab-ci.yml
- obs_static.sh
This pipeline job creates the static image files as they
would be needed in the obs system if a source service
is not allowed. This is usally the case for production
submissions. Thus the data on the artificats link in
gitlab now offers this data and can just be used to
drive these type of submissions
> Add obs artificats

- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
In SLE15 the install of the wheel group is no longer part
of the standard installation. This commit adds the explicit
install of the wheel group in all sle15 image descriptions
This Fixes #214
> Added system-group-wheel for sle15

- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
There was no syslog package in the sle15 image installed.
This lead to all kernel messages to be displayed on the
console. It became an issue with all the alua warning
messages that floods the console. This Fixes #202
> Added rsyslog to sle15 images

- azure_li_services/units/system_setup.py
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
- test/unit/units/system_setup_test.py
This patch is two fold
**Fixed High value calculation in kdump setup**
The High value should be calculated according to the recommendation from:
https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-tuning-kexec.html#sec-tuning-kexec-crashkernel. In addition we also take into account high memory systems which
recommends to add 2 bits for every 4 KB of RAM.This Fixes #203
**Update High value for kdump in VLI images**
Assume up to 16luns per machine and 224M High from kdumptool
calibration. This results in 232M which we set for the
very large instances as default now
> Fix kdump memory allocation

- images/li/sle15_sp2/config.kiwi
- images/vli/sle15_sp2/config.kiwi
As requested by jsc#SLE-10545, jsc#SLE-10902, jsc#SLE-10903,
jsc#ECO-817 and jsc#ECO-818. This commit adds the additional
monitoring modules for the LI and VLI images for SLE15-SP2.
As soon as the modules are available for older versions/SPs
we can add them there too
> Added prometheus monitoring modules

- images/li/sle12_sp3/config.kiwi
- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp5/config.kiwi
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
As requested by jsc#SLE-10545, jsc#SLE-10902, jsc#SLE-10903,
jsc#ECO-817 and jsc#ECO-818. This commit adds the additional
monitoring modules for the LI and VLI images for SLE12-SP3
and onward.
> Added prometheus monitoring modules for SLE12

- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
rsyslog is requested over syslog-ng for the VLI images
in SLE12. This Fixes #228
> Move to rsyslog for SLE12 VLI images

- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
As requested by jsc#SLE-10545, jsc#SLE-10902, jsc#SLE-10903,
jsc#ECO-817 and jsc#ECO-818. This commit update/adds the additional
monitoring modules for the LI and VLI images for SLE15-SP1/SP2
and GA
> Update prometheus monitoring modules for SLE15

- images/li/sle12_sp3/config.kiwi
- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp5/config.kiwi
- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
This change adds 'loglevel=3' to the kernel command line.
This is needed as a workaround to handing console messages
as a kthread. In certain cases there colud be a process block
while printing console messages. One viable worksround is to
adjust the loglevel to '3' to only show messages for "error,
critical, alert, and emergency."
> Fix printk timing issue

- images/li/sle15_sp2/root/etc/motd
- images/vli/sle15_sp2/root/etc/motd
The SLE15 SP2 images still have the version listed in the motd
file as SLE15 SP1. This patch updates the motd to match the installed
SLE15 SP2 version
> Fix motd SP version for SLE15 SP2 images

- images/li/sle15_sp2/config.kiwi
- images/vli/sle15_sp2/config.kiwi
…d to
Berkley DB and the SleepyCat license. Per request by SAP (jsc#PM-2071)
> Switch images to use rpm-ndb

- images/li/sle12_sp3/config.kiwi
- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp5/config.kiwi
- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
In order to run SAP applications which were compiled with GCC 7.x
the OS image needs to provide the correct gcc version. This
Fixes #238 and Fixes #218
> Added gcc7 to all LI/VLI images

- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
Some new kernel parameters due to a change of the hardware in the data center running the VLI images are needed. Provision
of the images to the new hardware is limited to the SLE15 code base. Thus only the SLE15 VLI images were changed
This Fixes #240
> Added requested VLI kernel parameters

- images/li/sle12_sp3/root/etc/dracut.conf.d/03-systemd.conf
- images/li/sle12_sp4/root/etc/dracut.conf.d/03-systemd.conf
- images/li/sle12_sp5/root/etc/dracut.conf.d/03-systemd.conf
- images/li/sle15_ga/root/etc/dracut.conf.d/03-systemd.conf
- images/li/sle15_sp1/root/etc/dracut.conf.d/03-systemd.conf
- images/li/sle15_sp2/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle12_sp3/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle12_sp4/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle12_sp5/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle15_ga/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle15_sp1/root/etc/dracut.conf.d/03-systemd.conf
- images/vli/sle15_sp2/root/etc/dracut.conf.d/03-systemd.conf
Make sure /etc/systemd/network configuration files are
included into the initrd such that the configured link
namePolicy becomes effectively set. This Fixes bsc#1176738
and Fixes #243
> Added dracut config 03-systemd.conf

- obs_static.sh
the job artifacts packs directories with 0777 which
could cause problems in chkstat on the later build
process.
> Fix permissions in obs overlay tarball

- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp5/config.kiwi
- images/li/sle15_ga/config.kiwi
- images/li/sle15_sp1/config.kiwi
- images/li/sle15_sp2/config.kiwi
- images/li/sle15_sp3/config.kiwi
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
- images/vli/sle15_sp3/config.kiwi
All LI/VLI images runs from a SAN storage via redundant
storage paths managed by multipath. The implicit check
for eventually existing multipath devices uncovered a
potential race condition if the multipath maps appears
too late. This is related to Issue #255. As a consequence
a fix in kiwi was made OSInside/kiwi#1641 which checks
for multipath maps until they appear or fail if they
don't appear after a timeout. This change requires an
image that is designed to run in a multipath environment
to explicitly request it, which is done in this PR
> Explicitly activate multipath lookup

- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp2/config.kiwi
- images/vli/sle15_sp3/config.kiwi
The option Nmi_watchdog was used for all VLI SLE15 images.
But the correct option names is nmi_watchdog. This is
related to bsc#1180817
> Fixed nmi watchdog kernel option

- images/li/sle15_sp3/config.kiwi
- images/vli/sle15_sp3/config.kiwi
Also on SLE15 SP3 an explicit selection for the YaST
UI interface is required. This fixes bsc#1182965
> Added explicit libyui curses package for YaST

- images/li/sle15_sp3/config.kiwi
- images/vli/sle15_sp3/config.kiwi
The autobuild team has recently implemented that feature in IBS.  Basically you add a line  to the config.kiwi that have rpm-ndb in their packages list and can live without the extra repository. reduces time in the scheduler spent in 15-SP3 by one third (removing one out of 3 repos ...)
> Use <!-- OBS-IgnorePackage: rpm --> in config.kiwi to handle rpm-ndb properly

- images/li/sle12_sp3/config.kiwi
- images/li/sle12_sp3/config.sh
- images/li/sle12_sp4/config.kiwi
- images/li/sle12_sp4/config.sh
- images/li/sle12_sp5/config.kiwi
- images/li/sle12_sp5/config.sh
- images/li/sle15_ga/config.sh
- images/li/sle15_sp1/config.sh
- images/li/sle15_sp2/config.sh
- images/li/sle15_sp3/config.sh
- images/vli/sle12_sp3/config.kiwi
- images/vli/sle12_sp3/config.sh
- images/vli/sle12_sp4/config.kiwi
- images/vli/sle12_sp4/config.sh
- images/vli/sle12_sp5/config.kiwi
- images/vli/sle12_sp5/config.sh
- images/vli/sle15_ga/config.kiwi
- images/vli/sle15_ga/config.sh
- images/vli/sle15_sp1/config.kiwi
- images/vli/sle15_sp1/config.sh
- images/vli/sle15_sp2/config.kiwi
- images/vli/sle15_sp2/config.sh
- images/vli/sle15_sp3/config.kiwi
- images/vli/sle15_sp3/config.sh
**Delete obsolete timezone setting**
This setting is done by kiwi via the respective timezone section
**Delete obsolete keyboard and console settings**
These settings are done by kiwi according to the locale and keyboard settings
**Delete inconsistent and wrong USED_FS_LIST setting**
For some reason, probably cut and paste an invalid setting in /etc/sysconfig/storage was applied
> Fix config settings inconsistencies
