SUSE-Enceladus/azure-li-services

azure_li_services/defaults.py
azure_li_services/units/config_lookup.py
test/unit/defaults_test.py
test/unit/units/config_lookup_test.py

The implementation is based on mounting a device by label
and lookup of a pre defined file name on the root of that
mount point. This Fixes #1 and This Fixes #2

Implement config lookup service

---

azure_li_services/command.py
azure_li_services/defaults.py
azure_li_services/exceptions.py
azure_li_services/instance_type.py
azure_li_services/network.py
azure_li_services/path.py
azure_li_services/runtime_config.py
azure_li_services/units/config_lookup.py
azure_li_services/units/network.py
azure_li_services/version.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-network.service
test/data/config.yaml
test/data/config_vli.yaml
test/unit/command_test.py
test/unit/defaults_test.py
test/unit/exceptions_test.py
test/unit/instance_type_test.py
test/unit/network_test.py
test/unit/runtime_config_test.py
test/unit/units/config_lookup_test.py
test/unit/units/network_test.py

Work through the networking section of the Azure Li/Vli config
file and setup the network configuration for this instance
type. This Fixes #4

Added azure-li-network service

---

azure_li_services/exceptions.py
azure_li_services/runtime_config.py
azure_li_services/units/user.py
azure_li_services/users.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-user.service
test/data/config.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py
test/unit/units/user_test.py
test/unit/users_test.py

Creates the configured user and its access setup for ssh
and sudo services in the scope of an Azure Li/Vli instance
This Fixes #6

Added User service

---

azure_li_services/runtime_config.py
azure_li_services/units/call.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-call.service
test/data/config.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py
test/unit/units/call_test.py

Read the call directive from the config file, mount the lun and calls the script
With great power comes great responsibility :smile:

Added script call service

---

azure_li_services/runtime_config.py
azure_li_services/units/install.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-install.service
test/data/config.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py
test/unit/units/install_test.py

Allow to install packages from local repository
This Fixes #7

Added package install service

---

azure_li_services/units/config_lookup.py
test/unit/units/config_lookup_test.py

Ensure /etc/suse_firstboot_config.yaml is at 0600

---

azure_li_services/exceptions.py
azure_li_services/runtime_config.py
azure_li_services/units/report.py
azure_li_services/units/storage.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-report.service
systemd/azure-li-storage.service
test/unit/runtime_config_test.py
test/unit/units/report_test.py
test/unit/units/storage_test.py

Updates fstab with new entries from the optional storage
section and activates the new mount locations.
__Note for myself__

Added storage service

---

.virtualenv.requirements.txt
azure_li_services/exceptions.py
azure_li_services/runtime_config.py
azure_li_services/schema.py
package/azure_li_services_spec_template
test/data/config.yaml
test/data/config_invalid.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py

Validate config file with a schema using the cerberus engine
This Fixes #31

Added schema validation for config file

---

systemd/azure-li-report.service

Make sure report service starts before getty

---

azure_li_services/units/call.py
azure_li_services/units/install.py
azure_li_services/units/storage.py

Fixup success state for optional services

---

azure_li_services/runtime_config.py
azure_li_services/schema.py
azure_li_services/units/system_setup.py
package/azure_li_services_spec_template
setup.py
systemd/azure-li-system-setup.service
test/data/config.yaml
test/data/config_invalid.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py
test/unit/units/system_setup_test.py

Along with the service the setup of the hostname has
been implemented. This Fixes #40

Added system_setup service

---

azure_li_services/runtime_config.py
azure_li_services/schema.py
azure_li_services/units/user.py
test/data/config.yaml
test/data/config_vli.yaml
test/unit/runtime_config_test.py
test/unit/units/user_test.py

Allow optional group_id in user data

---

azure_li_services/schema.py
azure_li_services/units/user.py
azure_li_services/users.py
test/data/config.yaml
test/unit/runtime_config_test.py
test/unit/units/user_test.py
test/unit/users_test.py

Allow to specify if the user password has to be changed on
next logon. This Fixes #121

Added optional require_password_change attribute

---

azure_li_services/runtime_config.py
azure_li_services/schema.py
azure_li_services/units/install.py
test/data/config.yaml
test/data/config_vli.yaml
test/data/config_vli_gen3.yaml
test/unit/runtime_config_test.py
test/unit/units/install_test.py

Allow to configure multiple repositories and formats not only
packages from a directory list. Specifically add packages to
install in an install section. This Fixes #120

Extend installer service

---

azure_li_services/defaults.py
azure_li_services/units/system_setup.py
test/unit/units/system_setup_test.py

It loads the module and make the load boot persistant
This Fixes #138

Load softdog module when STONITH is set up

---

azure_li_services/units/user.py
test/data/config.yaml
test/unit/runtime_config_test.py
test/unit/units/user_test.py

Allow access through ssh without shadow hash and
with shell.
Fixes #151

Allow ssh access with shell

---

azure_li_services/units/system_setup.py
test/unit/units/system_setup_test.py

Implementing startup sequence as suggested in SAP Note 1275776.
This Fixes #149

Apply saptune startup sequence suggested by $MS

---

azure_li_services/command.py

Implements a simple logging facility for the Command classes
and write the commands called to the console. This will lead
to more detailed information about the command calls in the
systemd status information

Log command calls on the console

---

azure_li_services/units/system_setup.py
test/unit/units/system_setup_test.py

sbd device to wait for udev to finish

---

azure_li_services/units/system_setup.py
test/unit/units/system_setup_test.py

There is no deterministic way to know when the iSCSI device
is ready to be processed by sbd. Thus the calls to setup the
sbd device has been placed into a retry loop that runs max
3 times with a 2sec wait period in between. This Fixes #188

Add retry loop to setup sbd device

---

images/vli/sle12_sp4/config.kiwi
images/vli/sle15_sp1/config.kiwi

Added Microsoft requested packages to VLI images

---

images/li/sle15_sp2/config.kiwi
images/vli/sle15_sp2/config.kiwi

- Requested in jsc#11453 (Deployment of HANA Scale-up Performance Optimized Scenario from Salt (SUMA 4.0)
- Requested in jsc#11454 (Automate setup of DRBD NFS-Share in SALT and Terraform)

Include salt formula packages etc. in SLES for SAP images

---

images/vli/sle15_ga/config.kiwi
images/vli/sle15_sp1/config.kiwi
images/vli/sle15_sp2/config.kiwi

Added missing java-1_8_0-ibm package. This Fixes #193

Added IBM java 1.8 to sle15 VLI image descriptions

---

images/li/sle12_sp4/config.kiwi
images/vli/sle12_sp4/config.kiwi

- numad
- libyui-qt-pkg7
This Fixes #208

Add requested packages to SLES 12 SP4

---

images/vli/sle15_sp1/root/etc/modprobe.d/50-azure-vli-blacklist.conf
images/vli/sle15_sp2/root/etc/modprobe.d/50-azure-vli-blacklist.conf

Modules blacklisted:
- ioatdma
- skx_edac
This Fixes #210

Blacklist modules to avoid emergency mode

---

images/vli/sle12_sp4/root/etc/modprobe.d/50-azure-vli-blacklist.conf
images/vli/sle12_sp5/root/etc/modprobe.d/50-azure-vli-blacklist.conf

Black listed ioatdma and skx_edac. This Fixes #225

Added VLI blacklist config for SLE12 images

---

images/li/sle12_sp3/root/etc/sysctl.d/91-hana-basenet.conf
images/li/sle12_sp4/root/etc/sysctl.d/91-hana-basenet.conf
images/li/sle12_sp5/root/etc/sysctl.d/91-hana-basenet.conf
images/li/sle15_ga/root/etc/sysctl.d/91-hana-basenet.conf
images/li/sle15_sp1/root/etc/sysctl.d/91-hana-basenet.conf
images/li/sle15_sp2/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle12_sp3/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle12_sp3/root/etc/sysctl.d/91-hana-netapp.conf
images/vli/sle12_sp4/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle12_sp4/root/etc/sysctl.d/91-hana-netapp.conf
images/vli/sle12_sp5/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle12_sp5/root/etc/sysctl.d/91-hana-netapp.conf
images/vli/sle15_ga/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle15_ga/root/etc/sysctl.d/91-hana-netapp.conf
images/vli/sle15_sp1/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle15_sp1/root/etc/sysctl.d/91-hana-netapp.conf
images/vli/sle15_sp2/root/etc/sysctl.d/91-hana-basenet.conf
images/vli/sle15_sp2/root/etc/sysctl.d/91-hana-netapp.conf

As requested this commit updates the SAP Hana settings
This Fixes #245

Update SAP Hana settings

---

images/li/sle12_sp3/config.kiwi
images/li/sle12_sp4/config.kiwi
images/li/sle12_sp5/config.kiwi
images/li/sle15_ga/config.kiwi
images/li/sle15_sp1/config.kiwi
images/li/sle15_sp2/config.kiwi
images/vli/sle12_sp3/config.kiwi
images/vli/sle12_sp4/config.kiwi
images/vli/sle12_sp5/config.kiwi
images/vli/sle15_ga/config.kiwi
images/vli/sle15_sp1/config.kiwi
images/vli/sle15_sp2/config.kiwi

Update image versions due to modifications done for
fixing Issues #245 and #243

bump image versions

---

images/li/sle12_sp3/config.kiwi
images/li/sle12_sp4/config.kiwi
images/li/sle12_sp5/config.kiwi
images/li/sle15_ga/config.kiwi
images/li/sle15_sp1/config.kiwi
images/li/sle15_sp2/config.kiwi
images/li/sle15_sp3/config.kiwi
images/vli/sle12_sp3/config.kiwi
images/vli/sle12_sp4/config.kiwi
images/vli/sle12_sp5/config.kiwi
images/vli/sle15_ga/config.kiwi
images/vli/sle15_sp1/config.kiwi
images/vli/sle15_sp2/config.kiwi
images/vli/sle15_sp3/config.kiwi

This will include HA setup information in the supportconfig tarball and aid
the support team in debugging issues.

Add supportutils-plugin-ha-sap

---

images/li/sle15_sp3/config.kiwi
images/vli/sle15_sp3/config.kiwi

+ Update image versions to 1.0.0 per convention
+ Ready for release

- 15 SP3 has reached GM
